version: '3'

services:
  redis:
    image: redis
    restart: always
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    ports:
      - 6379:6379
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
